"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var cors = require("cors");
var transcript3_model_1 = require("transcript3-model");
var CreateSession_1 = require("./operation/CreateSession");
var CreateAccount_1 = require("./operation/CreateAccount");
var app = express();
app.use(cors());
app.use(express.json());
app.post(transcript3_model_1.CreateAccountResource, CreateAccount_1.createAccountHandler);
app.post(transcript3_model_1.CreateSessionResource, CreateSession_1.createSessionHandler);
app.listen(3000);
