import { TranscriptRecord } from '../record/TranscriptRecord';
import { BaseTable } from './BaseTable';
export declare class TranscriptTable extends BaseTable {
    static readonly instance: TranscriptTable;
    private readonly TABLE_NAME;
    private readonly TRANSCRIPT_ID;
    private readonly ACCOUNT_EMAIL;
    private readonly SCHOOL_NAME;
    private readonly SCHOOL_ADDRESS;
    private readonly ADMIN_TITLE;
    private readonly ADMIN_NAME;
    private readonly ADMIN_PHONE;
    private readonly ADMIN_EMAIL;
    private readonly STUDENT_NAME_FIRST;
    private readonly STUDENT_NAME_MIDDLE;
    private readonly STUDENT_NAME_LAST;
    private readonly STUDENT_NAME_SUFFIX;
    private readonly STUDENT_BIRTH_DATE;
    private readonly STUDENT_ADDRESS;
    private readonly STUDENT_PHONE;
    private readonly STUDENT_EMAIL;
    private readonly TRANSCRIPT_TITLE;
    private readonly TRANSCRIPT_LOGO;
    private readonly ARRANGE_BY_GRADE;
    private readonly WEIGHTED_GPA;
    constructor();
    initialize(): Promise<void>;
    listTranscripts(accountEmail: string): Promise<TranscriptRecord[]>;
    putTranscript(record: TranscriptRecord): Promise<void>;
    updateTranscript(record: TranscriptRecord): Promise<void>;
    deleteTranscript(transcriptId: string): Promise<void>;
}
